version: '3.7'

services:
  app:
    build:
      context: .
      dockerfile: .devcontainer/Dockerfile

    environment:
      DATABASE_HOST: postgres

    volumes:
      - ..:/workspaces:cached

    command: /bin/sh -c "while sleep 1000; do :; done"
