name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  eslint:
    runs-on: ubuntu-20.04
    container:
      image: python:2.7.18-buster
    name: ESLint
    steps:
    - uses: actions/checkout@v3
    - uses: actions/setup-node@v3
      with:
        node-version: 10.13.x
    - name: Run install
      uses: borales/actions-yarn@v4
      with:
        cmd: install # will run `yarn install` command
    - name: Run lint
      uses: borales/actions-yarn@v4
      with:
        cmd: lint # will run `yarn test` command

  rails:
    runs-on: ubuntu-latest
    name: "ERBLint, ESCheck, and RSpec"
    env:
      DATABASE_HOST: postgres
      RAILS_ENV: test
    services:
      postgres:
        image: postgres:10.5-alpine
        env:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: sm_password
        # Set health checks to wait until postgres has started
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: 10.13.x
    - name: Precomple Rails assets
      run: bundle exec rails assets:precompile
    - name: Run ESCheck
      run: yarn es-check
    - name: Load the database schema
      run: bundle exec rake db:schema:load --trace
    - name: Migrate the database
      run: bundle exec rails db:migrate
    - name: Seed the database
      run: bundle exec rails db:seed
    - name: Run the RSpec test suite
      run: bundle exec rspec

  ruby_linting:
    runs-on: ubuntu-latest
    name: Brakeman and Rubocop
    env:
      BUNDLE_ONLY: lint
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    # TODO: Migrate to use Docker image
    # when Brakeman can be updated.
    - run: bundle exec brakeman -q -w2
    - run: bundle exec rubocop --format progress
