name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  javascript_and_erb:
    runs-on: ubuntu-latest
    name: "ESLint and ERBLint"
    steps:
    - name: Install required apt packages
      run: sudo apt-get install -yqq python2
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: 10.13.x
        cache: 'yarn'
    - name: Run yarn install
      run: yarn install

    - name: Run ESLint
      run: yarn lint
    - name: Run ERBLint
      run: yarn lint-erb

  escheck_rails:
    runs-on: ubuntu-latest
    name: "ESCheck and RSpec"
    services:
      postgres:
        image: postgres:10.5-alpine
        env:
          POSTGRES_USER: sm
          POSTGRES_PASSWORD: sm_password
        # Set health checks to wait until postgres has started
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - uses: actions/setup-node@v3
      with:
        node-version: 10.13.x
        cache: 'yarn'
    - name: Precomple Rails assets
      run: bundle exec rails assets:precompile
    - name: Run yarn es-check
      uses: borales/actions-yarn@v4
      with:
        cmd: es-check
    - name: Setup DB and run RSpec
      env:
        DATABASE_HOST: postgres
        RAILS_ENV: test
      run: |-
        bundle exec rails db:create
        bundle exec rake db:schema:load --trace
        bundle exec rails db:migrate
        bundle exec rails db:seed
        bundle exec rspec

  ruby_linting:
    runs-on: ubuntu-latest
    name: Ruby Linting
    steps:
    - uses: actions/checkout@v3
    - uses: ruby/setup-ruby@v1
      with:
        bundler-cache: true
    - run: bundle exec brakeman -q -w2
    - run: bundle exec rubocop --format progress --format github
